server:
   port: 4001
   #servlet:
        #context-path: /Microservices
spring:
  application:
      name: Microservices-1
  datasource:
    url:      jdbc:mysql://localhost:3306/microservices
    username: root
    password: giridb
    driverClassName: com.mysql.cj.jdbc.Driver
  # Spring Data JPA configuration
  #jpa:
    #hibernate:
      # To be updated in real production usage!
      #ddl-auto: update
    #show-sql: true
    
